version: '3.9'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    env_file:
      - src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend_nw

volumes:
  postgres_data:

networks:
  backend_nw:
    driver: bridge
