# Generated by Django 4.1.1 on 2022-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Подтвержден"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_chat_id",
            field=models.PositiveIntegerField(verbose_name="Telegram chat-id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_user_id",
            field=models.PositiveIntegerField(verbose_name="Telegram user-id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(max_length=6, verbose_name="Код подтверждения"),
        ),
    ]
