# Generated by Django 4.1.1 on 2022-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_alter_tguser_tg_chat_id_alter_tguser_tg_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="tg_chat_id",
            field=models.BigIntegerField(verbose_name="Telegram chat-id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_user_id",
            field=models.BigIntegerField(verbose_name="Telegram user-id"),
        ),
    ]
