# Generated by Django 4.1.1 on 2022-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0006_alter_goal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Описание"
            ),
        ),
    ]
