# Generated by Django 4.1.1 on 2022-10-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0011_alter_goalcategory_board"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardparticipant",
            options={"verbose_name": "Участник", "verbose_name_plural": "Участники"},
        ),
    ]
